stages:
  - test
  - release

build-windows-vs2017:
  script:
    - call tools\release_vs2017.bat
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - windows
    - vs2017
  only:
    - web
  artifacts:
    paths:
      - release\killerbeez-*.zip
    expire_in: 1 week
  stage: release

build-windows-vs2019:
  script:
    - call tools\release_vs2019.bat
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - windows
    - vs2019
  only:
    - web
  artifacts:
    paths:
      - release\killerbeez-*.zip
    expire_in: 1 week
  stage: release

release-linux:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make release
  image: killerbeez-builder:latest
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - ubuntu-16.04
  only:
    - web
  artifacts:
    paths:
      - build/killerbeez-*.zip
    expire_in: 1 week
  stage: release

# Smoke tests on all platforms
.smoketest-linux: &smoketest-linux
  script:
    - cd ..
    - killerbeez/tests/smoke_test.sh
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    - web
  stage: test
  # The build is broken on most of the platforms
  allow_failure: true

smoketest-ubuntu-14.04:
  <<: *smoketest-linux
  tags:
    - ubuntu-14.04

smoketest-ubuntu-16.04:
  <<: *smoketest-linux
  tags:
    - ubuntu-16.04
  # This platform is supposed to be working
  allow_failure: false

smoketest-ubuntu-18.04:
  <<: *smoketest-linux
  tags:
    - ubuntu-18.04

smoketest-ubuntu-19.04:
  <<: *smoketest-linux
  tags:
    - ubuntu-19.04

smoketest-fedora-29:
  <<: *smoketest-linux
  tags:
    - fedora-29

smoketest-fedora-30:
  <<: *smoketest-linux
  tags:
    - fedora-30

smoketest-debian-8:
  <<: *smoketest-linux
  tags:
    - debian-8

smoketest-debian-9:
  <<: *smoketest-linux
  tags:
    - debian-9

smoketest-debian-10:
  <<: *smoketest-linux
  tags:
    - debian-10
